config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'  # This is referred to using 'root_path'

  get 'help' => 'static_pages#help' # These are named routes
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'addapage' => 'static_pages#howtoadd'
  get 'login' => 'sessions#new' #URL: /login, NAMEDROUTE: login_path, ACTION: new, page for new sessions
  post 'login' => 'sessions#create' #URL: /login, NAMEDROUTE: login_path, Action: create, create new sessions (login)
  delete 'logout' => 'sessions#destroy' #URL: /logout, NAMEDROUTE: logout_path, Action: destroy, delete session (logout)
  
=begin
Browsers request pages from Rails by making a request for a URL using a specific HTTP method, such as GET, POST, PATCH, PUT and DELETE. 
Each method is a request to perform an operation on the resource. A resource route maps a number of related requests to actions in a single controller.
When your Rails application receives an incoming request for --> DELETE /photos/17 it asks the router to map it to a controller action. 
If the first matching route is --> resources :photos Rails would dispatch that request to the destroy method on the photos controller with { id: '17' } in params.

HTTP  | Path	         |Controller#Action|    Named Route     	|        Used for
GET	  |/photos	       |photos#index	   |photos_path           |display a list of all photos
GET	  |/photos/new	   |photos#new	     |new_photo_path        |return an HTML form for creating a new photo
POST  |/photos	       |photos#create	   |photos_path           |create a new photo
GET	  |/photos/:id	   |photos#show	     |photo_path(photo)     |display a specific photo
GET	  |/photos/:id/edit|photos#edit	     |edit_photo_path(photo)|return an HTML form for editing a photo
PATCH |/photos/:id     |photos#update    |photo_path(photo)     |update a specific photo
DELETE|/photos/:id	   |photos#destroy   |photo_path(photo)     |delete a specific photo
=end 
  resources :users do # This is a RESTful resource that comes with CRUD, analagous to HTML's: POST, GET, PATCH, DELETE
    member do # get method to arrange for the URLs to respond appropriately. Meanwhile, the member method arranges 
      get :followers, :following
    end
  end
  resources :account_activation, only: [:edit]
  resources :password_resets,    only: [:new, :create, :edit, :update]
  resources :microposts,         only: [:create, :destroy]
  resources :relationships,      only: [:create, :destroy]
  
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,         only: [:edit, :update]
  before_action :valid_user,       only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]
  
  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email]) #Look up user in nested hash
    # :password_reset from form then :email from password_reset
      if @user # If user is valid
        @user.create_reset_digest
        @user.send_password_reset_email
        flash[:info] = "Email sent to #{@user.email} with password reset instructions."
      redirect_to root_url
      else
        flash[:danger] = "Email not found."
        render 'new'
      end
  end
  
  def edit
    
  end
  
  def update
    if params[:user][:password].empty?
        @user.errors.add(:password, "Password can't be empty")
        render 'edit'
      elsif @user.update_attributes(user_params)
        log_in @user
        flash[:success] = "Password Updated Successfully"
        redirect_to @user
      else
        render 'edit'
    end
  end
  
private
  
  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  
# Before Filters 

  def get_user
    @user = User.find_by(email: params[:email])
  end
  
  def valid_user 
    unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
      redirect_to root_url
    end
  end
  
  def check_expiration # Check expiration of reset token
    if @user.password_reset_expired?
      flash[:danger] = "Password reset link has expired"
      redirect_to new_password_reset_url
    end
  end
  
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide :title, "Password Reset" %>

<h1>Reset your password</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            
            <%= hidden_field_tag :email, @user.email %>
            
            <%= f.label :password %>
            <%= f.password_field :password %>
            
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            
            <%= f.submit "Update Password", class: "btn btn-primary" %>
            
        <% end %>
    </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot Password") %>

<h1>Enter your email to have a reset link sent</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(:password_reset, url: password_resets_path) do  |f| %>
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
            
            <%= f.submit "Submit", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>