config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'  # This is referred to using 'root_path'

  get 'help' => 'static_pages#help' # These are named routes
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'addapage' => 'static_pages#howtoadd'
  get 'login' => 'sessions#new' #URL: /login, NAMEDROUTE: login_path, ACTION: new, page for new sessions
  post 'login' => 'sessions#create' #URL: /login, NAMEDROUTE: login_path, Action: create, create new sessions (login)
  delete 'logout' => 'sessions#destroy' #URL: /logout, NAMEDROUTE: logout_path, Action: destroy, delete session (logout)
  
=begin
Browsers request pages from Rails by making a request for a URL using a specific HTTP method, such as GET, POST, PATCH, PUT and DELETE. 
Each method is a request to perform an operation on the resource. A resource route maps a number of related requests to actions in a single controller.
When your Rails application receives an incoming request for --> DELETE /photos/17 it asks the router to map it to a controller action. 
If the first matching route is --> resources :photos Rails would dispatch that request to the destroy method on the photos controller with { id: '17' } in params.

HTTP  | Path	         |Controller#Action|    Named Route     	|        Used for
GET	  |/photos	       |photos#index	   |photos_path           |display a list of all photos
GET	  |/photos/new	   |photos#new	     |new_photo_path        |return an HTML form for creating a new photo
POST  |/photos	       |photos#create	   |photos_path           |create a new photo
GET	  |/photos/:id	   |photos#show	     |photo_path(photo)     |display a specific photo
GET	  |/photos/:id/edit|photos#edit	     |edit_photo_path(photo)|return an HTML form for editing a photo
PATCH |/photos/:id     |photos#update    |photo_path(photo)     |update a specific photo
DELETE|/photos/:id	   |photos#destroy   |photo_path(photo)     |delete a specific photo
=end 
  resources :users do # This is a RESTful resource that comes with CRUD, analagous to HTML's: POST, GET, PATCH, DELETE
    member do # get method to arrange for the URLs to respond appropriately. Meanwhile, the member method arranges 
      get :followers, :following
    end
  end
  resources :account_activation, only: [:edit]
  resources :password_resets,    only: [:new, :create, :edit, :update]
  resources :microposts,         only: [:create, :destroy]
  resources :relationships,      only: [:create, :destroy]
  
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? # .any is just like the opposite of .empty? # %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form submitted contains <%= pluralize(object.errors.count, "error") %>.
        <% # Pluralize not auto-allowed, must 'include ActionView::Helpers::TextHelper' # %>
        </div>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class= "microposts">
<!-- Rails knows to call _microposts.html.erb since each elements of @feed_items is of the Micropost ckass -->
<!-- Rails will look for a partial with a corresponding name in the views directory of the given resource -->
        <%= render @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: {  multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="Picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<!-- JQuery script below monitors CDD id micropost_picture, if it changes then this fires -->
<!-- Does not prevent upload, user could edit JS or issue a POST request using curl -->
<script type="text/javascript"> 
  $('#micropost_picture').bind('change', function () {
    var size_in_megabytes = this.files[0].size/1024/1024;
        if(size_in_megabytes > 5) {
          alert('Max file size is 5 MB. Please upload a smaller file.');
        }
  });
</script>

app/views/shared/_stats.html.erb
<!-- Since we include stats on both user pages and home page we use ||= -->
<!-- if @user isn't nil (ie. profile page) then uses it, otherwise it sets @user to current_user (ie. home) -->
<% @user ||= current_user %>
<div class="stats">
    <a href="<%= following_user_path(@user) %>">
        <strong id="following" class="stat">
            <%= @user.following.count %>
        </strong>
        Following
    </a>
    <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
            <%= @user.followers.count %>
        </strong>
        Followers
    </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 120), current_user %>

<h1><%= current_user.name %></h1>

<span><%= link_to "View Profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>