config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'  # This is referred to using 'root_path'

  get 'help' => 'static_pages#help' # These are named routes
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'addapage' => 'static_pages#howtoadd'
  get 'login' => 'sessions#new' #URL: /login, NAMEDROUTE: login_path, ACTION: new, page for new sessions
  post 'login' => 'sessions#create' #URL: /login, NAMEDROUTE: login_path, Action: create, create new sessions (login)
  delete 'logout' => 'sessions#destroy' #URL: /logout, NAMEDROUTE: logout_path, Action: destroy, delete session (logout)
  
=begin
Browsers request pages from Rails by making a request for a URL using a specific HTTP method, such as GET, POST, PATCH, PUT and DELETE. 
Each method is a request to perform an operation on the resource. A resource route maps a number of related requests to actions in a single controller.
When your Rails application receives an incoming request for --> DELETE /photos/17 it asks the router to map it to a controller action. 
If the first matching route is --> resources :photos Rails would dispatch that request to the destroy method on the photos controller with { id: '17' } in params.

HTTP  | Path	         |Controller#Action|    Named Route     	|        Used for
GET	  |/photos	       |photos#index	   |photos_path           |display a list of all photos
GET	  |/photos/new	   |photos#new	     |new_photo_path        |return an HTML form for creating a new photo
POST  |/photos	       |photos#create	   |photos_path           |create a new photo
GET	  |/photos/:id	   |photos#show	     |photo_path(photo)     |display a specific photo
GET	  |/photos/:id/edit|photos#edit	     |edit_photo_path(photo)|return an HTML form for editing a photo
PATCH |/photos/:id     |photos#update    |photo_path(photo)     |update a specific photo
DELETE|/photos/:id	   |photos#destroy   |photo_path(photo)     |delete a specific photo
=end 
  resources :users do # This is a RESTful resource that comes with CRUD, analagous to HTML's: POST, GET, PATCH, DELETE
    member do # get method to arrange for the URLs to respond appropriately. Meanwhile, the member method arranges 
      get :followers, :following
    end
  end
  resources :account_activation, only: [:edit]
  resources :password_resets,    only: [:new, :create, :edit, :update]
  resources :microposts,         only: [:create, :destroy]
  resources :relationships,      only: [:create, :destroy]
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        
        <% if logged_in? %>
          <li><%= link_to "All Friends", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
              <ul class="dropdown-menu"> <!-- Must enable Bootstrap's JS library for this in app/assets/JS/application.js -->
                <li><%= link_to "Profile", current_user %><!-- # could also use user_path(current_user) --></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                
                <li class="divider"></li>
                <li>
                  <%= link_to "Log Out", logout_path, method: :delete %> <!-- #or use "delete"??, we have to pass a method here to delete session -->
                </li>
              </ul>
          </li>
          
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
          
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=  full_title(yield(:title))  %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %> <%# render is a rails helper, looks for file in app/views/layouts/_shim.html.erb and insert results into the view %>
      <div class="container">      <%# leading underscores indicate partials %>
        
        <% flash.each do | message_type, message | %>
          <%= content_tag(:div, message, class:"alert alert-#{message_type}") %>
                  <% # Returns an HTML block tag of type name surrounding the content. Add HTML attributes by passing an attributes hash to options. %>
            <% # :success is a symbol, but embedded Ruby automatically converts it to the string "success" %>
            <% # Bootstrap CSS supports styling for four such flash classes (success, info, warning, and danger) %>
        <% end %>
        
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
        <%= debug('') %>

      </div>
  </body>
</html>